// src/components/ShareCard.tsx
"use client";

import * as React from "react";
import type { Outfit } from "@/lib/engine/types";

type Props = {
  outfit: Outfit;
  onClose: () => void;
};

const labelColors: Record<string, { bg: string; text: string; accent: string }> = {
  Safe: { bg: "#0a0a0a", text: "#ffffff", accent: "#e5e5e5" },
  Colorful: { bg: "#1a0a2e", text: "#ffffff", accent: "#c084fc" },
  Bold: { bg: "#0a1628", text: "#ffffff", accent: "#60a5fa" },
};

const occasionEmoji: Record<string, string> = {
  work: "💼",
  date: "🌹",
  casual: "☀️",
  night_out: "🌙",
  travel: "✈️",
  gym: "💪",
};

export default function ShareCard({ outfit, onClose }: Props) {
  const cardRef = React.useRef<HTMLDivElement>(null);
  const [copied, setCopied] = React.useState(false);
  const [sharing, setSharing] = React.useState(false);

  const colors = labelColors[outfit.label] ?? labelColors.Safe;
  const emoji = occasionEmoji[outfit.occasion] ?? "✨";

  const occasionLabel = outfit.occasion.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

  // Share text
  const shareText = `${emoji} My ${occasionLabel} outfit today — generated by OutfitMirror\n\n👕 ${String(outfit.picks.top.type).replace(/_/g, " ")}\n👖 ${String(outfit.picks.bottom.type).replace(/_/g, " ")}\n👟 ${String(outfit.picks.shoes.type).replace(/_/g, " ")}\n\nStyle: ${outfit.label} • Score: ${outfit.score}/100\n\n#OutfitMirror #OOTD #MensFashion`;

  async function handleCopyText() {
    try {
      await navigator.clipboard.writeText(shareText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setCopied(false);
    }
  }

  async function handleShare() {
    if (navigator.share) {
      setSharing(true);
      try {
        await navigator.share({
          title: "My OutfitMirror Look",
          text: shareText,
          url: "https://outfitmirror.com",
        });
      } catch {
        // user cancelled
      } finally {
        setSharing(false);
      }
    } else {
      // fallback - copy text
      handleCopyText();
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm">
      <div className="w-full max-w-sm">

        {/* CARD - story format */}
        <div
          ref={cardRef}
          style={{ backgroundColor: colors.bg }}
          className="relative overflow-hidden rounded-3xl p-8 text-white aspect-[9/16] max-h-[70vh] flex flex-col justify-between"
        >
          {/* Background decoration */}
          <div
            style={{ backgroundColor: colors.accent + "15" }}
            className="absolute -top-20 -right-20 w-64 h-64 rounded-full blur-3xl"
          />
          <div
            style={{ backgroundColor: colors.accent + "10" }}
            className="absolute -bottom-20 -left-20 w-64 h-64 rounded-full blur-3xl"
          />

          {/* Top section */}
          <div className="relative z-10">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs font-semibold uppercase tracking-widest" style={{ color: colors.accent }}>
                  OutfitMirror
                </p>
                <p className="text-xs mt-0.5" style={{ color: colors.text + "80" }}>
                  {emoji} {occasionLabel}
                </p>
              </div>
              <div
                className="rounded-full px-3 py-1 text-xs font-bold"
                style={{ backgroundColor: colors.accent + "20", color: colors.accent }}
              >
                {outfit.label}
              </div>
            </div>

            {/* Score */}
            <div className="mt-6">
              <p className="text-6xl font-black" style={{ color: colors.text }}>
                {outfit.score}
                <span className="text-2xl font-normal" style={{ color: colors.text + "60" }}>/100</span>
              </p>
              <p className="mt-1 text-sm" style={{ color: colors.text + "60" }}>outfit score</p>
            </div>
          </div>

          {/* Middle - outfit items */}
          <div className="relative z-10 space-y-3">
            {[
              { emoji: "👕", label: "Top", value: outfit.picks.top },
              { emoji: "👖", label: "Bottom", value: outfit.picks.bottom },
              { emoji: "👟", label: "Shoes", value: outfit.picks.shoes },
            ].map((item) => (
              <div
                key={item.label}
                className="rounded-2xl p-4 flex items-center gap-3"
                style={{ backgroundColor: colors.accent + "12" }}
              >
                <span className="text-2xl">{item.emoji}</span>
                <div>
                  <p className="font-semibold capitalize" style={{ color: colors.text }}>
                    {String(item.value.type).replace(/_/g, " ")}
                  </p>
                  <p className="text-xs capitalize" style={{ color: colors.text + "60" }}>
                    {item.value.color_family}
                  </p>
                </div>
              </div>
            ))}
          </div>

          {/* Bottom */}
          <div className="relative z-10">
            <div className="flex items-center gap-2">
              <div className="h-px flex-1" style={{ backgroundColor: colors.accent + "30" }} />
              <p className="text-xs" style={{ color: colors.text + "50" }}>outfitmirror.com</p>
              <div className="h-px flex-1" style={{ backgroundColor: colors.accent + "30" }} />
            </div>
            <p className="mt-2 text-center text-xs" style={{ color: colors.text + "40" }}>
              #OutfitMirror #OOTD #MensFashion
            </p>
          </div>
        </div>

        {/* Action buttons */}
        <div className="mt-4 grid grid-cols-2 gap-3">
          <button
            className="rounded-xl bg-white px-4 py-3 text-sm font-medium text-black hover:bg-white/90 transition"
            onClick={handleCopyText}
            type="button"
          >
            {copied ? "✅ Copied!" : "📋 Copy Text"}
          </button>

          <button
            className="rounded-xl bg-white px-4 py-3 text-sm font-medium text-black hover:bg-white/90 transition disabled:opacity-50"
            onClick={handleShare}
            disabled={sharing}
            type="button"
          >
            {sharing ? "Sharing..." : "📤 Share"}
          </button>
        </div>

        <button
          className="mt-3 w-full rounded-xl border border-white/20 px-4 py-3 text-sm text-white hover:bg-white/10 transition"
          onClick={onClose}
          type="button"
        >
          Close
        </button>
      </div>
    </div>
  );
}